name: Create Docker image
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'ci skip:')" # If the commit contains "ci skip" this action won't run
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get short SHA
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          push: true
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tags: hl-resistance/backend/discord-bot:latest, hlresistance/backend/discord-bot:sha-${{ steps.vars.outputs.sha_short }}